version: '3'
services:
  visual_robot_localization:
    image: visual_robot_localization:0.0.1
    network_mode: "host"
    ipc: "host"
    pid: "host"
    stdin_open: true
    tty: true
    environment:
      - SDL_VIDEODRIVER=x11
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - "ROS_DOMAIN_ID=42"
      - "FASTRTPS_DEFAULT_PROFILES_FILE=/opt/visual_robot_localization/networking/fastrtps-profile.xml"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
      - type: bind
        source: ./../visual_robot_localization/
        target: /opt/visual_robot_localization/src/visual_robot_localization
      - type: bind
        source: ${HOME}/Hierarchical-Localization/outputs/
        target: /opt/visual_robot_localization/src/visual_robot_localization/hloc_outputs/
      - type: bind
        source: ${HOME}/Hierarchical-Localization/datasets/
        target: /opt/visual_robot_localization/src/visual_robot_localization/hloc_datasets/
      - ./networking:/opt/visual_robot_localization/networking
      - ./../visualization:/opt/visual_robot_localization/visualization
  
    shm_size: 8gb
    runtime: nvidia
    container_name: visual_robot_localization

    command: bash -c ". /opt/ros/foxy/setup.sh && colcon build && . install/setup.sh && nvidia-smi && echo $ROS_DOMAIN_ID && ros2 launch visual_robot_localization Spot_DLAB.launch.py"

  ros1_bridge:
    image: ros:foxy-ros1-bridge
    network_mode: "host"
    ipc: "host"
    pid: "host"

    environment:
      - "ROS_HOSTNAME=${ROS_HOSTNAME}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "ROS_DOMAIN_ID=42"
      - "FASTRTPS_DEFAULT_PROFILES_FILE=/opt/visual_robot_localization/networking/fastrtps-profile.xml"
    volumes:
      - ./networking:/opt/visual_robot_localization/networking
    command:  ros2 run ros1_bridge dynamic_bridge
